### PR TITLE
[CPM-198] notes front end

### PR DESCRIPTION
**Pull request by Richardng12**
## Changes

- Notes frontend saved to backend

## Checklist

- [x] Have tests been written?
- [x] Is the UI consistent?

## Requests
- [x] Can somebody check the styling/CSS?

Addresses [CPM-198]

Connects #y

[CPM-198]: https://momentum-agile.atlassian.net/browse/CPM-198

### CODE REVIEW

**Comment by FocalChord** [comment]
@pull-dog up

**Review by daltonlim — APPROVED** [review]
hacktoberfest-accepted

**Review by FocalChord — APPROVED** [review]
PRRRRRRRRRRRRRRRRRRRRRRRRRETY PRO

**Review by Dinith1 — APPROVED** [review]
LGTM 🦖

**Pull request merged**
