### PR TITLE
[CPM-149] Search Bar Overlap Fix

### PR DESCRIPTION
**Pull request by Richardng12**
## Changes

- Changed Z index so search bar doesnt go on top
- smallest pr 👍 
hIR82det9l

## Checklist

- [x] Have tests been written?
- [x] Is the UI consistent?

## Requests
- [ ] Can somebody check the styling/CSS?

Addresses [CPM-149]

[CPM-149]: https://momentum-agile.atlassian.net/browse/CPM-149

### CODE REVIEW

**Review by FocalChord — APPROVED** [review]
great work as always chief

**Comment by daltonlim** [comment]
Bro don't steal my ticket like that

**Comment by Richardng12** [comment]
> 
> 
> Bro don't steal my ticket like that 😭

I made the ticket hahaha

**Review by daltonlim — APPROVED** [review]
LGTM

**Pull request merged**
