### PR TITLE
[CPM-95] Add real courses to database seeder

### PR DESCRIPTION
**Pull request by daltonlim**

### CODE REVIEW

**Review by HongShi10 — APPROVED** [review]
Good Job seeding looks good!

**Review by HongShi10 — CHANGES_REQUESTED** [review]
Actually with the new course regulation PR the models that are being seeded will need to be changed please look at the new course data model

**Review by FocalChord — APPROVED** [review]
LGTM boss, will be nice to finally get some actual information!

**Review by Richardng12 — APPROVED** [review]
Good job on changing the courses.json layout to the new schema!@!@!@

**Pull request merged**
