### PR TITLE
[CPM-40] Drag and Drop Courses on Plan Page

### PR DESCRIPTION
**Pull request by FocalChord**
## Changes

- Added react-dnd packages
- Integrated DND with course table and pill

## Checklist

- [x] Is the UI consistent?

## Requests
- [ ] Can somebody check the styling/CSS?

Addresses [CPM-40]

[CPM-40]: https://momentum-agile.atlassian.net/browse/CPM-40

### CODE REVIEW

**Comment by daltonlim** [comment]
Should we be able to drag courses between semesters?

**Review by HongShi10 — APPROVED** [review]
lgtm

**Comment by FocalChord** [comment]
@daltonlim Will make a ticket for that

**Review by daltonlim — APPROVED** [review]
Lgtm

**Comment by FocalChord** [comment]
Todo: Check CSS

**Pull request merged**
