### PR TITLE
[CPM-134] Update courses and students pages to use common search bar

### PR DESCRIPTION
**Pull request by Dinith1**
## NOTE:
- The UI is still yet to be update
- Only the search bars were changed in this task

## Changes
- OLD
pr1
- NEW
pr2

- OLD
pr3
- NEW
pr4

## Checklist

- [ ] Have tests been written?
- [x] Is the UI consistent?

Addresses [CPM-134]

Connects #y

[CPM-134]: https://momentum-agile.atlassian.net/browse/CPM-134

### CODE REVIEW

**Comment by FocalChord** [comment]
That uhh button spacing is a bitt off chief

Screen Shot 2020-09-21 at 2 09 00 PM

**Comment by Dinith1** [comment]
> That uhh button spacing is a bitt off chief
> 
> Screen Shot 2020-09-21 at 2 09 00 PM

Yea this PR is just to use the common components, the CSS is yet to be updated. We're just trying to do preliminary tasks to make our lives easier

**Review by vee-christella — APPROVED** [review]
Great work sir 🧢

**Review by HongShi10 — APPROVED** [review]
lgtm need tests later too

**Pull request merged**
