### PR TITLE
[CPM-76] API Tests for programme degree

### PR DESCRIPTION
**Pull request by Richardng12**
- Added API tests for programme-degree
- Edited programme-degree routes PUT req to return updated programme-degree instead of the old one
- Changed defaultPlan fieldto programme-degree model to be of type [object]

### CODE REVIEW

**Review by HongShi10 — COMMENTED** [review]
Do we need a test for post programme degree without a name?

**Comment by Richardng12** [comment]
> 
> 
> Do we need a test for post programme degree without a name?

its not required in the model, should i maek it so?

**Review by HongShi10 — APPROVED** [review]
LGTM

**Review by wryao64 — APPROVED** [review]
LGTM

**Pull request merged**
