### PR TITLE
[CPM-109] delete course

### PR DESCRIPTION
**Pull request by HongShi10**

### CODE REVIEW

**Review by FocalChord — APPROVED** [review]
good work hong

**Review by FocalChord — CHANGES_REQUESTED** [review]
Nevermind, after what Nasseer said we need this hidden away but still visible lol.

**Review by Dinith1 — APPROVED** [review]
Very clean! LGTM :shipit:

**Comment by HongShi10** [comment]
> Nevermind, after what Nasseer said we need this hidden away but still visible lol.

we should do this in another PR

**Review by vee-christella — APPROVED** [review]
I can take on the refactoring of the delete button positioning 👍

**Review by FocalChord — APPROVED** [review]
gj

**Pull request merged**
