### PR TITLE
test

### PR DESCRIPTION
**Pull request by FocalChord**
test

### CODE REVIEW

**Comment by daltonlim** [comment]
Yes

**Comment by FocalChord** [comment]
testing this pull-dog thing lol

**Comment by ffMathy** [comment]
@FocalChord @daltonlim hi there! I'm the creator of Pull Dog - a small one-man startup (https://www.indiehackers.com/product/dogger) trying to gain traction :sweat_smile:

Did everything work as you expected here? Is there anything that stops you from using it in the future, or is everything alright?

Getting feedback is so hard. That's why I'm manually writing out to people, to try to get all the feedback I can!

**Comment by FocalChord** [comment]
@ffMathy Hi your product worked fine but I was having trouble configuring the backend host URL dynamically as an environment variable in the docker-compose.yml file into the frontend application :(

**Comment by ffMathy** [comment]
Ah interesting use-case! That makes a lot of sense.

Can you describe this a bit further? Because we can probably make it happen!

Would it work if there was an environment variable and build argument set on all Pull Dog environments, which would include the hostname? That way, you could read the hostname at runtime, but also during build.

It could be called `PULL_DOG_HOSTNAME`.

That way, your Dockerfile could look like this:

```
FROM node:14-alpine

ARG PULL_DOG_HOSTNAME
ENV PULL_DOG_HOSTNAME=${PULL_DOG_HOSTNAME}

//anywhere in the Dockerfile you would be able to refer to ${PULL_DOG_HOSTNAME} to get the hostname of the server.
//and during runtime, you could refer to the environment variable ${PULL_DOG_HOSTNAME} as well.

WORKDIR /app
COPY package.json .

RUN yarn
COPY . .

CMD ["yarn", "start"]
```

Would that work for you?

I think it would only take half an hour to make, and it's indeed a useful feature.

**Comment by FocalChord** [comment]
@ffMathy How would that apply in my `docker-compose.yml` file? The backend also has to be connected to a mongodb server so that host has to be dynamic too

**Comment by ffMathy** [comment]
I made #83 now where it works. You can see the changes I made there, to support it.

Was that what you meant?

Also see this PR of my fork, where Pull Dog is running correctly: https://github.com/ffMathy/course-planner/pull/1

**Comment by ffMathy** [comment]
I should mention that it only seems to do the first `students` call correctly, but the subsequent `student` call seems to fail. But that must be due to some other bug, and unrelated to Pull Dog. This shows how to get started on getting it working.

If you are interested, I can debug further?

**Comment by FocalChord** [comment]
I checked out the PR on the branch and it seems the frontend is still calling the `localhost:8080` endpoint. Also, we won't be able to afford the next level of pull dog as this is for a university project and we are all students so don't worry too much about it, I think the first level only allows one open PR which might be too less for us :)

**Comment by ffMathy** [comment]
Hmmm yes, it seems like it is only taking the environment variable the first couple of times, and then stops using it after some time. Perhaps because it's the dev server of React?

As for the pricing, the free plan allows for more PRs. You can just only have one concurrent test environment at a time. If you open an additional one, it'll say you have run out. But you can go into that PR and run `@pull-dog down`, and then `@pull-dog up` in your other PR, to have your instance help out somewhere else.

You can also set up a timeout by adding a `pull-dog.json` file to your repo, so that your environments kill themselves off after some time, freeing up the slot you have for another PR.

In addition, as for the pricing level, I can offer a 75% discount on all plans for the account that is using Pull Dog for this repository. I want to emphasize that the free plan will still work for you guys.

I started looking into getting it to work consistently. I'll let you know when it's done and ready for another spin. Even if you decide not to go with this, it's still an important feature for me to support, so I'll work on it either way, and won't be hurt if you then decide not to use it, despite the above clarification 😄

**Comment by ffMathy** [comment]
Alright, I got it working now: http://34.245.154.196:3000/ (from the PR I linked above).

It turned out the environment variable needed to begin with `REACT_APP_`, which is a React safety measure.

**Comment by FocalChord** [comment]
@ffMathy Wow thank you so much for your help, I really appreciate you making the PR. Since this is a university project, we are not allowed to merge external PR's in so I have to make a seperate PR but I will definitely integrate it in! Thanks for all the help :D

**Comment by ffMathy** [comment]
You're very welcome @FocalChord! I'm a developer like you guys, so if you are ever missing a feature or want some technical assistance, let me know!

And thank you for trying this out. Feel free to make feature requests over at our repo!

**Comment by ffMathy** [comment]
Oh, and let me know if you are interested in that 75% discount I can give you! 👍

**Pull request closed without merging**
