### PR TITLE
[CPM-135] Students page renovation

### PR DESCRIPTION
**Pull request by Dinith1**
## Changes
- Before:
image

- After:
image

## Checklist
- [ ] Have tests been written?
- [x] Is the UI consistent?

## ACs:
- [x] Table should be similar to the newly updates Courses table
- [x] Move plans button to the bottom of page
- [x] Make title of RHS the student
- [x] Add student button should be consistent with courses page
- [x] Change BG of LHS to courses
- [x] Student information should be Left-Aligned
- When creating a new student/editing existing student:
  - [x] When entering a UPI or ID incorrectly, the popup error message should say what the format should be, e.g. “jsmi123”/“123456789”
  - [ ] Could also add a question-mark icon + tooltip to next to each input title to show an example UPI/ID
  - [x] Add edit to the options menu instead of inline
  - [x] Remove year level in create student

## Requests
- [ ] Can somebody check the styling/CSS?

Addresses [CPM-135]

Connects #y

[CPM-135]: https://momentum-agile.atlassian.net/browse/CPM-135

### CODE REVIEW

**Comment by FocalChord** [comment]
@pull-dog up

**Review by FocalChord — APPROVED** [review]
looks yum now, cheers matey

**Comment by daltonlim** [comment]
@pull-dog up

**Review by wryao64 — APPROVED** [review]
LGTM

**Comment by ffMathy** [comment]
@pull-dog up

**Pull request merged**
