### PR TITLE
[CPM-132] Existing programmes UI Renovation

### PR DESCRIPTION
**Pull request by vee-christella**
## Changes

This PR is pretty hefty as it fixes a lot of loose ends and renovates the Programmes page, including: 
- The LHS of the Programmes list, including colours and background
- Existing Programmes page title
- Replace Title with the programme name
- Remove Programme Name
- Style tables to look better
- Instead of adding the requirements tab, use part of the table [inline] instead of being a separate component
- Make box bigger
- Define Template should be static and never shift
- Change the regulation rows to white
- Thin line to separate regulations
- Order of options menu swapped to 
    1. Edit
    2. Delete
- Just general refactoring 

| Feature |Pre-master | This PR |
|---|---|---|
|Overview of Existing Programme | image | image |
| Editing an existing Programme| image | image |
| Creating a new regulation |  image | image image |
| Editing a regulation | image | image |

What this PR **doesn't** cover:
- Editing is inconsistent with student and programme pages (edit button vs inline editing)
- Creating a programme still doesn't allow regulation creation in the same step
- Switching between programmes in edit mode doesn't cancel the edit mode (but still discards changes)

## Checklist

- [x] Have tests been written?
- [x] Is the UI consistent?

## Requests
- [ ] Can somebody check the styling/CSS?

**Please suggest any visual changes in this PR!** Ideally we'd like to avoid any more visual changes with these renovations

Addresses [CPM-132]

Connects #y

[CPM-132]: https://momentum-agile.atlassian.net/browse/CPM-132

### CODE REVIEW

**Comment by FocalChord** [comment]
Holy crap that UI is soooo NICE

**Comment by FocalChord** [comment]
Just one nitpick thing: I feel like there is a lot of whitespace after the "from" text and also the buttons at the end.

Is there anyway of making them fit nicer so that there is a larger space for the course pills?

Screen Shot 2020-09-24 at 8 38 50 PM

**Comment by vee-christella** [comment]
> Is there anyway of making them fit nicer so that there is a larger space for the course pills?

Definitely! I did it this way to align the "FROM" with the rest of the regulations under it though. If you think real estate rules over consistency I'm happy to change it 😁

**Comment by FocalChord** [comment]
This is looks on mine, is this intended:

Screen Shot 2020-09-24 at 8 50 31 PM

**Review by Dinith1 — APPROVED** [review]
VERY nice! :shipit:

**Review by FocalChord — APPROVED** [review]
☝️ 😋 💯 🥇

**Pull request merged**
