### PR TITLE
[CPM-183] update programmes page

### PR DESCRIPTION
**Pull request by wryao64**
## Changes

- removed 'Define Template' button from programme creation page
- renamed Requirements to Regulations

## Checklist

- [x] Have tests been written?
- [x] Is the UI consistent?

## Requests
- [ ] Can somebody check the styling/CSS?

Addresses [CPM-183]

[CPM-183]: https://momentum-agile.atlassian.net/browse/CPM-183

### CODE REVIEW

**Comment by daltonlim** [comment]
Should regulations still appear on define tempalte?
image

**Review by daltonlim — APPROVED** [review]
LGTM

**Comment by vee-christella** [comment]
Hey @wryao64 , I think this ticket is redundant now since we're changing the create programmes to be a modal instead 😢 Sorry that it's a sudden change - but we already have [CPM-102] as the programmes page renovation ticket! Are you okay to close this?

**Comment by wryao64** [comment]
Yup all good

**Pull request closed without merging**
