### PR TITLE
[CPM-182] Sorting of Courses

### PR DESCRIPTION
**Pull request by FocalChord**
Merge 176 first

## Changes

- When you get courses from UoA API, they are now sorted!
- You can also sort the tables by clicking on the column [Students Page, Courses Page], See GIF to see it in action

sorting

## Checklist

- [x] Have tests been written?
- [ ] Is the UI consistent?

## Requests
- [x] Can somebody check the styling/CSS? 

Addresses [CPM-182]

[CPM-182]: https://momentum-agile.atlassian.net/browse/CPM-182

### CODE REVIEW

**Review by daltonlim — APPROVED** [review]
LGTM. Great work with the jiff

**Comment by Dinith1** [comment]
@FocalChord Would it be possible to use a different icon for the sorting arrows in the table, ideally one that fits with the theme

**Review by Dinith1 — APPROVED** [review]
LGTM 🦖 

But just two little things:
- Would it be possible to make the sorting arrows nicer looking?
- Would it be possible to prevent the table resizing horizontally when sorting by `points`?

**Comment by FocalChord** [comment]
See CPM-194 for ticket I made regarding the issue, someone sle can fix the styling

**Pull request merged**
