### PR TITLE
[CPM-120] Fix courses display on programme regulations

### PR DESCRIPTION
**Pull request by anian100**

### CODE REVIEW

**Comment by FocalChord** [comment]
Can you take a quick picture of how it looks now?

**Comment by anian100** [comment]
> Can you take a quick picture of how it looks now?

image

**Comment by daltonlim** [comment]
Looks good. Just wondering if you could add small crosses or something to indicate that clicking the button removes the course from regulations.

**Review by daltonlim — APPROVED** [review]
LGTM

**Review by FocalChord — APPROVED** [review]
🚢

**Pull request merged**
