### PR TITLE
[CPM-62] Apply programme plan to student

### PR DESCRIPTION
**Pull request by daltonlim**
## Changes

- Creating a plan for a student now uses the default plan for the given programme.

## Checklist

- [x] Have tests been written?
- [x] Is the UI consistent?

## Requests
- [ ] Can somebody check the styling/CSS?

Addresses [CPM-62]

Connects #y

[CPM-62]: https://momentum-agile.atlassian.net/browse/CPM-62

### CODE REVIEW

**Review by vee-christella — APPROVED** [review]
LGTM!

**Comment by vee-christella** [comment]
Actually, @daltonlim  can you please add a Toast whenever the user creates a plan and a default template is applied?

**Comment by daltonlim** [comment]
> Actually, @daltonlim can you please add a Toast whenever the user creates a plan and a default template is applied?

done

**Review by FocalChord — APPROVED** [review]
🚢  :shipit: 😋

**Pull request merged**
