### PR TITLE
[CPM-131] Change 'Fixes' to 'Addresses'

### PR DESCRIPTION
**Pull request by Dinith1**
## Changes
- Update PR template
- Change 'Fixes' to 'Addresses

- Addresses [CPM-131]

[CPM-131]: https://momentum-agile.atlassian.net/browse/CPM-131

### CODE REVIEW

**Review by FocalChord — APPROVED** [review]
love ur work 🚢

**Review by daltonlim — APPROVED** [review]
LGTM 🔢

**Comment by vee-christella** [comment]
Can you change it to either tag you or me for design approval?

**Comment by Dinith1** [comment]
> Can you add to it to specify to either tag you or me for design approval?

What do you mean?

**Pull request merged**
