### PR TITLE
[CPM-202] Remove courses from dropdown as they're added to a regulation

### PR DESCRIPTION
**Pull request by Dinith1**
## Changes

- Courses are now removed from the dropdown when as they are added to a regulation for a programme

## Checklist

- [ ] Have tests been written?
- [ ] Is the UI consistent?

## Requests
- [ ] Can somebody check the styling/CSS?

Addresses [CPM-202]

Connects #y

[CPM-202]: https://momentum-agile.atlassian.net/browse/CPM-202

### CODE REVIEW

**Comment by wryao64** [comment]
Can you please rebase? All the cleanup commits have been merged to pre-master in PR #144

**Review by wryao64 — CHANGES_REQUESTED** [review]
Can you please rebase? All the cleanup commits have been merged to pre-master in PR #144

**Review by wryao64 — APPROVED** [review]
LGTM

**Review by Richardng12 — APPROVED** [review]
big plays by the man himself

**Pull request merged**
