### PR TITLE
[CPM-170] Enable autoscroll to a given course

### PR DESCRIPTION
**Pull request by daltonlim**
## Changes

- Ugly empty div warning removed
- Table now autoscrolls to a course given its url

## Checklist

- [x] Have tests been written?
- [x] Is the UI consistent?

## Requests
- [ ] Can somebody check the styling/CSS?

Addresses [CPM-170]

Connects #y

[CPM-170]: https://momentum-agile.atlassian.net/browse/CPM-170

### CODE REVIEW

**Comment by FocalChord** [comment]
What does React.forwardRef do?

**Comment by daltonlim** [comment]
> What does React.forwardRef do?

@FocalChord passes the ref downwards so that it appears in a Dom as opposed to a functional component

**Review by FocalChord — APPROVED** [review]
tested on mine, looks good 👍

**Review by Richardng12 — APPROVED** [review]
works for me lgtm

**Pull request merged**
