### PR TITLE
[CPM-157] Integrating pull dog

### PR DESCRIPTION
**Pull request by FocalChord**
This PR changes the Client dockerfile to integrate the pull dog environment variable into the React. After the API Client URL has been modified! :D

### CODE REVIEW

**Comment by FocalChord** [comment]
🐶

**Review by daltonlim — CHANGES_REQUESTED** [review]
Please add a description

**Review by Dinith1 — APPROVED** [review]
LGTM

**Review by daltonlim — APPROVED** [review]

**Review by wryao64 — APPROVED** [review]
LGTM

**Pull request merged**
